1.  Write a NumPy program to reverse an array (first element becomes last).

In [2]:
import numpy as np
import numpy as np
x = [1, 2, 3, 4 ,5]
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[1, 2, 3, 4, 5]
Reverse array:
[5, 4, 3, 2, 1]


2.   Write a NumPy program to create a 2-dimensional array of size 2 x 3 also print the shape, type and data type of the array.

In [4]:
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print("Type: ", type(x))	
print("Shape: ", x.shape)
print("Data Type: ", x.dtype)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)
Data Type:  int32


3.   Write a NumPy program to create a 2-D array with ones on the diagonal and zeros elsewhere.

In [5]:
import numpy as np
x =  np.diagflat([1, 1, 1])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


4.   Write a NumPy program to multiply and add two 3 x 3 matrices.

In [10]:
import numpy as np
p = [[1, 0, 2], [0, 1, 3], [2, 1, 1]]
q = [[1, 2, 3], [3, 4, 1], [3, 3, 1]]
result1 = np.dot(p, q)
result2 = np.add(p,q)
print("Multiplication:\n" ,result1)
print("Addition:\n" ,result2)

Multiplication:
 [[ 7  8  5]
 [12 13  4]
 [ 8 11  8]]
Addition:
 [[2 2 5]
 [3 5 4]
 [5 4 2]]


5.   Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.

In [15]:
import numpy as np
angle = [0., 30., 45., 60., 90.]
print("sine:")
print(np.sin(angle) * np.pi / 180.)
print("cosine:")
print(np.cos(angle) * np.pi / 180.)
print("tangent:")
print(np.tan(angle) * np.pi / 180.)

sine:
[ 0.         -0.0172444   0.01485107 -0.00531995  0.01560319]
cosine:
[ 0.01745329  0.0026922   0.0091686  -0.01662274 -0.00782036]
tangent:
[ 0.         -0.11179412  0.02827041  0.00558576 -0.03482282]


6.   Write a NumPy program to compute e^x, element-wise of a given array.


In [17]:
import numpy as np
x = np.array([1., 2., 3., 4.], np.float32)
print("Original array: ")
print(x)
print("e^x:")
r = np.exp(x)
print(r)

Original array: 
[1. 2. 3. 4.]
e^x:
[ 2.718282   7.3890557 20.085537  54.59815  ]
